/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'msgType' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
  'text' : IDL.Text,
  'sender' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const SignalingData = IDL.Record({
  'answerSDP' : IDL.Opt(IDL.Text),
  'iceCandidatesAnswerer' : IDL.Vec(IDL.Text),
  'offerSDP' : IDL.Opt(IDL.Text),
  'iceCandidatesOfferer' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addIceCandidateAnswerer' : IDL.Func([IDL.Text], [], []),
  'addIceCandidateOfferer' : IDL.Func([IDL.Text], [], []),
  'clearMessages' : IDL.Func([], [], []),
  'clearSignaling' : IDL.Func([], [], []),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getSignaling' : IDL.Func([], [IDL.Opt(SignalingData)], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'storeAnswer' : IDL.Func([IDL.Text], [], []),
  'storeOffer' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'msgType' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
    'text' : IDL.Text,
    'sender' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const SignalingData = IDL.Record({
    'answerSDP' : IDL.Opt(IDL.Text),
    'iceCandidatesAnswerer' : IDL.Vec(IDL.Text),
    'offerSDP' : IDL.Opt(IDL.Text),
    'iceCandidatesOfferer' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addIceCandidateAnswerer' : IDL.Func([IDL.Text], [], []),
    'addIceCandidateOfferer' : IDL.Func([IDL.Text], [], []),
    'clearMessages' : IDL.Func([], [], []),
    'clearSignaling' : IDL.Func([], [], []),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getSignaling' : IDL.Func([], [IDL.Opt(SignalingData)], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'storeAnswer' : IDL.Func([IDL.Text], [], []),
    'storeOffer' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };